#ifndef GRANULATOR_BUILD_INFO_H
#define GRANULATOR_BUILD_INFO_H

#define APP_VERSION "0.01"
#define APP_GIT_HASH "UNKNOWN"
#define APP_GIT_DIRTY ""
#define APP_BUILD_ID "V" APP_VERSION " " APP_GIT_HASH APP_GIT_DIRTY

#endif
